image: docker:19.03.12

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.12-dind

before_script:
  - docker info

stages:
  - build
  - trigger

build:
  stage: build
  only: [ branches ]
  script:
    - apk add openssl
    - export VERSION=v$(date +%s)
    - export IMAGE_VERSION=$CI_REGISTRY_IMAGE:$VERSION
    - export IMAGE_REF=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_VERSION -t $IMAGE_REF .
    - docker push $IMAGE_VERSION
    - docker push $IMAGE_REF

trigger:
  stage: trigger
  trigger:
    project: staffs-msc/sep/deployment
